version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
        - ./nginx/logs:/var/www/http/logs/
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/nginx/ssl
        - ./http:/var/www/http
    networks:
      - bridge
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "11004:11004"
    volumes:
      - ./v2ray:/etc/v2ray
  golang:
    container_name: golang
    build: ./go
    ports:
      - "8088:8088"
    volumes:
      - ./http:/var/www/http
    tty: true
networks:
  bridge:
    driver: bridge