version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
        - ./nginx/logs:/var/www/logs/
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/nginx/ssl
        - /var/www/http:/var/www/http
    networks:
      - bridge
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "11004:11004"
    volumes:
      - ./v2ray:/etc/v2ray
  golang:
    container_name: golang
    build: ./go
    ports:
      - "8088:8088"
    volumes:
      - ./http:/var/www/http
    tty: true
  es:
    container_name: es
    build: ./es
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - '9200:9200'     #java、集群通信端口
      - '9300:9300'     #http通信端口
    networks:
      - bridge
networks:
  bridge:
    driver: bridge